export const GENERAL_TYPES = {
    NUMBER: "NUMBER",
    STRING: "STRING",
    BOOLEAN: "BOOLEAN",
    DATE: "DATE",
    OBJECT: "OBJECT",
    ARRAY: "ARRAY",
    ONCLICK: "ONCLICK",
    ONCHANGE: "ONCHANGE"
}